### PR TITLE
Optifine Crash fixes / Render improvements

### LINKED ISSUE #139: Crash From RenderAttackHelicopter while using Optfine
i got this crash as i got near the ship that spawns the attack Helicopter i was using optfine i know not every mod dev supports optfine but i wish i could at least disable the helicopter as a temp fix but its not a option. 

mc 1.12.2 
forge 2838
techguns-1.12.2-2.0.1.2_1
OptiFine_1.12.2_HD_U_E3
[crash-2019-06-28_19.15.11-client.txt](https://github.com/pWn3d1337/Techguns2/files/3341219/crash-2019-06-28_19.15.11-client.txt)

### PR DESCRIPTION
**Pull request by ben-mkiv**
This PR addresses Client crashes with the Attack Helicopter and 40mm Projectile when Optifine is installed.

this PR would fix #139 and #131 

edit: added a small fix for the bioblob block which turned the screen black if you stood in the same block

added textures with real transparency (old textures but with real alpha)

### CODE REVIEW

**Comment by pWn3d1337** [comment]
seems fine. I will look at it closer on the next weekend.

**Comment by pWn3d1337** [comment]
There is a conflict on the testscope.png, that needs to be resolved before merging. It seems you did not pull my last push.

**Comment by ben-mkiv** [comment]
done

**Comment by pWn3d1337** [comment]
Have you used a specific shader setup that works? I tried with Optifine + SEUS and all effects are wrong. But Optifine seems to work, good work on that!

**Comment by ben-mkiv** [comment]
this PR doesn't address the Optifine Shader improvements yet, as i was about to submit them in a separate PR when im done with them.

**Pull request merged**
